apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-api
  labels:
    app: hw
spec:
  replicas: 4
  selector:
    matchLabels:
      name: hw
  template:
    metadata:
      labels:
        name: hw
    spec:
      containers:
        - name: api
          image: yegemberdin/hw1api
          livenessProbe:
            httpGet:
              path: /task_lists
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /task_lists
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 10
---            
apiVersion: v1
kind: Service
metadata:
  name: hw
spec:
  ports:
    - port: 8000
  selector:
    name: hw
  type: NodePort